/* Run: NODE_PATH=<jsdom installation>/node_modules node tests/solomon-submissions.test.cjs */
const fs=require('fs'),assert=require('node:assert/strict'),crypto=require('crypto'),{JSDOM}=require('jsdom');
const src=p=>fs.readFileSync(p,'utf8');
const pass=Buffer.from(src('js/solomon-demo-gate.js').match(/BAKED_PASSCODE = atob\('([^']+)'/)[1],'base64');
async function fetchJson(p){if(!fs.existsSync(p+'.enc'))return JSON.parse(src(p));const b=fs.readFileSync(p+'.enc'),key=crypto.pbkdf2Sync(pass,b.subarray(4,20),200000,32,'sha256'),d=crypto.createDecipheriv('aes-256-gcm',key,b.subarray(20,32));d.setAuthTag(b.subarray(-16));return JSON.parse(Buffer.concat([d.update(b.subarray(32,-16)),d.final()]));}
const tick=()=>new Promise(r=>setTimeout(r,10));
(async()=>{
 const dom=new JSDOM(src('solomon-islands-research-database-master.html'),{url:'https://ronvave.github.io/vave-lab/solomon-islands-research-database-master.html',runScripts:'outside-only'}),w=dom.window;w.console={...console,error:()=>{}};w.dbGate={fetchJson,boot:()=>{}};w.fetch=async p=>({ok:true,json:()=>fetchJson(p)});w.alert=msg=>{throw Error(msg);};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.remove();};
 w.eval(src('js/solomon-database-adapter.js'));
 const dashboard=src('js/solomon-database-master.js');const pos=dashboard.lastIndexOf('})();');w.eval(dashboard.slice(0,pos)+'window.testSolomon={state,loadAll,renderScholarCard,renderItemCard,renderStats,renderWorldPanel};'+dashboard.slice(pos));
 await w.testSolomon.loadAll();const state=w.testSolomon.state;
 const profile=Array.from(state.scholarProfilesByName.values()).find(p=>p.photo&&state.scholarInsights[p.name]);assert(profile,'Profile with saved photo and insight');
 const token='a'.repeat(40);let sent=[],enabled=true;w.fetch=async(url,options)=>({ok:true,json:async()=>{if(url.includes('solomon-share-tokens'))return{country:'Solomon Islands',m:{[profile.scholarId]:token}};if(url.includes('submissionCapabilities'))return{status:'ok',country:'Solomon Islands',spreadsheetId:'1um6pHKriEhbtvmkm7e8E1j0_Zt9A-oYpY88fuPoAmFY',publicSubmissionsEnabled:enabled};sent.push(JSON.parse(options.body));return{status:'ok',submissionId:'TEST'};}});
 w.SolomonSubmissionConfig={endpoint:'https://script.google.com/macros/s/fixture/exec',spreadsheetId:'1um6pHKriEhbtvmkm7e8E1j0_Zt9A-oYpY88fuPoAmFY'};
 w.eval(src('js/solomon-scholar-portal.js'));w.__solomonSharedScholar={scholarId:profile.scholarId,token};w.testSolomon.renderStats();w.testSolomon.renderWorldPanel();await w.SolomonScholarPortal.renderShared(state,w.testSolomon.renderScholarCard,w.testSolomon.renderItemCard);
 assert.equal(w.document.querySelectorAll('.db-scholar-card').length,1);assert(w.document.querySelector('.db-scholar-card__photo').getAttribute('style').includes(profile.photo));assert(w.document.querySelector('.db-scholar-card__insight-summary').textContent.length>80);assert(!w.document.querySelector('#db-embed-b3-chord'));
 assert.equal(w.document.querySelectorAll('.solomon-summary').length,3);assert.match(w.document.querySelector('.solomon-portal-intro').textContent,/Solomon Islands/);assert(!/Kaili|Hafoka|Tongan/.test(w.document.querySelector('.solomon-portal-intro').textContent));assert.match(w.document.querySelector('.solomon-publications-head').textContent,/planning and decision making/);assert.equal(w.document.querySelector('[data-kpi="db-works"]').textContent,Number(state.snapshot.items.length).toLocaleString());assert(!w.document.querySelector('[data-b2-kpis]').textContent.includes('—'));
 const linked=new Set(state.master.authorship.filter(a=>a['Scholar ID']===profile.scholarId).map(a=>a['Publication ID / BibTeX Key']));const expected=state.snapshot.items.filter(it=>linked.has(it._masterPublicationId));assert(expected.length>0);assert.equal(w.document.querySelectorAll('.solomon-geo-toolbar').length,expected.length);
 await w.SolomonScholarPortal.openUpdate(profile,state);let form=w.document.querySelector('dialog form');assert.equal(form.querySelectorAll('.solomon-geography-paternal input,.solomon-geography-paternal select').length,3);assert.equal(form.querySelectorAll('.solomon-geography-maternal input,.solomon-geography-maternal select').length,3);assert(![...form.querySelectorAll('.solomon-geography-maternal input')].some(n=>n.value));const byLabel=s=>[...form.querySelectorAll('label')].find(l=>l.childNodes[0].textContent===s).querySelector('input,select,textarea');byLabel('Your name').value='Test reviewer';byLabel('Your email').value='test@example.invalid';byLabel('Relationship to this scholar').value='Self';byLabel('Professional title').value='Test changed title';await form.onsubmit({preventDefault(){}});assert.equal(sent.length,1);assert.deepEqual(Object.keys(sent[0].fields),['title']);assert.equal(sent[0].structuredSubmission.changedFieldsOnly,true);assert(!JSON.stringify(sent[0]).includes('secret'));assert(!w.document.querySelector('dialog'),'Successful submission closes automatically');assert.match(w.document.querySelector('.solomon-submission-confirmation').textContent,/submitted successfully.*TEST/);await form.onsubmit({preventDefault(){}});assert.equal(sent.length,1,'Completed form cannot resubmit');
 const toolbars=[...w.document.querySelectorAll('.solomon-geo-toolbar')];assert(expected.length>1);assert.equal(w.document.querySelectorAll('.solomon-geotag').length,0);
 const pick=(toolbar,value)=>{const cb=[...toolbar.querySelectorAll('input[type=checkbox]')].find(c=>c.value===value);assert(cb,'Option '+value);assert(!cb.disabled);cb.checked=true;cb.dispatchEvent(new w.Event('change',{bubbles:true}));return cb;};
 const national=pick(toolbars[0],'national');pick(toolbars[0],'Fiji');const other=toolbars[0].querySelector('.solomon-geo-other');other.value='Jamaica; China; china';other.dispatchEvent(new w.Event('input',{bubbles:true}));
 const second=pick(toolbars[1],'province:Western');assert.match(w.document.querySelector('.solomon-geo-dirty-count').textContent,/2 publications/);
 second.checked=false;second.dispatchEvent(new w.Event('change',{bubbles:true}));assert.match(w.document.querySelector('.solomon-geo-dirty-count').textContent,/1 publication changed/);pick(toolbars[1],'province:Western');
 const details=toolbars[0].querySelector('details');details.open=true;w.document.querySelector('.solomon-publications-head').click();assert(!details.open);details.open=true;details.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!details.open);
 form=w.document.querySelector('.solomon-geo-submit');byLabel('Your name').value='Test reviewer';byLabel('Your email').value='test@example.invalid';byLabel('Relationship to this scholar').value='Self';
 enabled=false;await form.onsubmit({preventDefault(){}});assert.equal(sent.length,1);assert(national.checked);assert.match(form.querySelector('[role=status]').textContent,/not open yet/);assert.match(w.document.querySelector('.solomon-geo-dirty-count').textContent,/2 publications/);
 enabled=true;await form.onsubmit({preventDefault(){}});assert.equal(sent[1].changes.length,2);assert.equal(sent[1].changes[0].item_key,expected[0]._masterPublicationId);assert.equal(sent[1].changes[0].solomon_locations[0].national,true);assert.deepEqual(sent[1].changes[0].pacific_countries,['Fiji']);assert.deepEqual(sent[1].changes[0].other_countries,['Jamaica','China']);assert(national.disabled);assert.match(w.document.querySelector('.solomon-geo-dirty-count').textContent,/0 publications/);await form.onsubmit({preventDefault(){}});assert.equal(sent.length,2,'No duplicate submission');
 enabled=false;await w.SolomonScholarPortal.openUpdate(profile,state);form=w.document.querySelector('dialog form');byLabel('Your name').value='Test reviewer';byLabel('Your email').value='test@example.invalid';byLabel('Relationship to this scholar').value='Self';byLabel('Professional title').value='Another title';await form.onsubmit({preventDefault(){}});assert.equal(sent.length,2);assert.match(w.document.querySelector('dialog [role=status]').textContent,/not open yet/);
 console.log('PASS: inline national/island/Pacific/world geography, multi-publication submission, retained failed entries, no duplicate submission; shared profile preserves photo/insight, renders correct linked publications, submits changed fields only, uses Master publication ID, respects disabled submission gate.');dom.window.close();
 const admin=new JSDOM('<button data-tab="scholar-submissions"></button><button data-tab="geography-submissions"></button><div data-solomon-queue="scholar"></div><div data-solomon-queue="geography"></div>',{runScripts:'outside-only'}),a=admin.window;let approvals=[];a.confirm=()=>true;
 a.adminWriteback={isConfigured:()=>true,readScholarSubmissions:async()=>({status:'ok',rows:[{'Submission ID':'S1','Scholar ID':'SOL-S0001','Scholar Name':'<img src=x onerror=alert(1)>',Status:'Pending',proposedChanges:[{key:'title',label:'Title',currentValue:'Old',newValue:'New',writable:true},{key:'phd_year',label:'Year',currentValue:'',newValue:'2024',writable:false,reason:'Multiple degrees'}]}]}),reviewCapabilities:async()=>({status:'ok',combinedReview:true}),beginScholarReview:async(...args)=>{approvals.push(args);return{status:'ok',plan:{items:[]}};},finishScholarReview:async()=>({status:'ok',remainingReview:false}),readGeographySubmissions:async()=>({status:'ok',rows:[]})};a.eval(src('js/solomon-submissions-admin.js'));a.document.querySelector('[data-tab="scholar-submissions"]').click();await tick();assert(!a.document.querySelector('img'));const checks=a.document.querySelectorAll('input');assert(checks[0].checked&&!checks[0].disabled);assert(checks[1].disabled);[...a.document.querySelectorAll('.solomon-review-actions button')].find(b=>b.textContent==='Approve all checked').click();await tick();assert.equal(approvals.length,1);assert.equal(approvals[0][1].length,1);assert.equal(approvals[0][1][0].expectedCurrent,'Old');console.log('PASS: Admin escapes submitted text, excludes nonwritable fields, sends expected-current values.');admin.window.close();
})().catch(e=>{console.error(e);process.exit(1);});
