const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('crypto'),{JSDOM}=require('jsdom');
const src=p=>fs.readFileSync(p,'utf8'),ctx={console};vm.createContext(ctx);vm.runInContext(src('apps-script/deployed/tonga-submissions-v1.gs'),ctx);
ctx.jsonOut_=x=>x;ctx.tongaPlanSignature_=p=>crypto.createHmac('sha256','fixture').update(JSON.stringify(p)).digest('base64');ctx.tongaNow_=()=> 'fixture';ctx.LockService={getScriptLock:()=>({waitLock(){},releaseLock(){}})};
let current={title:'Old',gender:'M'},writes=0,logs=[];
const o={'Submission ID':'S1','Scholar ID':'TNG-S0001',Status:'Pending','Structured Submission JSON':'{}','Submitted Fields JSON':'{}','Attachments JSON':'[]',_row:5};
o._sheet={getRange:(r,c)=>({setValue:v=>{if(c===11)o['Structured Submission JSON']=v;if(c===3)o.Status=v;},setValues:()=>{}})};
ctx.geoSs_=()=>({});ctx.findScholarSubmission_=()=>o;ctx.appendChangeLog_=(...a)=>logs.push(a);
ctx.buildScholarSubmissionChanges_=()=>['title','gender'].filter(k=>current[k]!==({title:'New',gender:'F'})[k]).map(k=>({key:k,label:k,worksheet:'Scholars',field:k,currentValue:current[k],newValue:({title:'New',gender:'F'})[k],writable:true}));
ctx.applyOneChange_=(ss,c,dry)=>{if(current[c.field]===c.newValue)return{status:'already_satisfied'};if(current[c.field]!==c.oldValue)return{status:'needs_confirmation'};if(!dry){current[c.field]=c.newValue;writes++;}return{status:'ok'};};
const request=(changes)=>ctx.tongaReviewSelection_({submissionId:'S1',selectedChanges:changes,selectedFiles:[],reviewNotes:'fixture'});
let out=request([{key:'title',expectedCurrent:'Old'}]);assert.equal(current.title,'New');assert.equal(current.gender,'M');assert.equal(out.remainingReview,true);assert.equal(out.row.Status,'Pending');assert.equal(out.plan.items.find(x=>x.key==='gender').state,'deferred');
out=request([{key:'title',expectedCurrent:'Old'}]);assert.equal(writes,1,'Lost acknowledgement retry is idempotent');
current.gender='Changed elsewhere';assert.throws(()=>request([{key:'gender',expectedCurrent:'M'}]),/Master changed/);assert.equal(writes,1);current.gender='M';
out=request([{key:'gender',expectedCurrent:'M'}]);assert.equal(out.remainingReview,false);assert.equal(o.Status,'Reviewed');assert.equal(writes,2);assert.equal(request([{key:'gender',expectedCurrent:'M'}]).alreadyRecorded,true);
for(const bad of ['Jerusalem','Jerusalem-Tonga','Jerusalem - Tonga','Isra','Isreal'])assert.throws(()=>ctx.tongaList_([bad]),/Invalid country/);
assert.deepEqual(JSON.parse(JSON.stringify(ctx.tongaList_(['Israel','israel','USA']))),['Israel','United States of America']);
assert.equal(ctx.TongaCountries.rows.length,248);assert.equal(ctx.TongaCountries.resolve('Nauru').m49,'520');assert.equal(ctx.TongaCountries.suggest('Isra')[0].name,'Israel');
console.log('PASS single-request selected review, deferred fields, retry, changed Master conflict, complete status, canonical server country validation');
(async()=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://fixture.invalid',runScripts:'outside-only'}),w=dom.window;w.confirm=()=>true;w.eval(src('js/tonga-countries.js'));w.eval(src('js/tonga-country-inputs.js'));
 const parent=w.document.getElementById('root');let changes=0;let editor=w.TongaCountryInputs(parent,'TNG-S1:P1',()=>changes++);
 const count=parent.querySelector('input[type=number]');count.value=5;count.dispatchEvent(new w.Event('change'));assert.equal(parent.querySelectorAll('.tonga-country-row').length,5);
 const inputs=parent.querySelectorAll('.tonga-country-row input');['Isra','Jerusalem-Tonga','China','china',''].forEach((v,i)=>{inputs[i].value=v;inputs[i].dispatchEvent(new w.Event('input'));inputs[i].dispatchEvent(new w.Event('blur'));});
 assert(parent.querySelector('datalist option[value="Israel"]'));assert.equal(inputs[1].getAttribute('aria-invalid'),'true');assert.equal(editor.invalid().length,2);assert.deepEqual(Array.from(editor.values()),['China']);
 inputs[0].value='Israel';inputs[0].dispatchEvent(new w.Event('blur'));assert.equal(inputs[0].getAttribute('aria-invalid'),'false');assert.deepEqual(Array.from(editor.values()),['Israel','China']);
 parent.replaceChildren();editor=w.TongaCountryInputs(parent,'TNG-S1:P1',()=>{});editor.restore();assert.equal(parent.querySelectorAll('.tonga-country-row').length,5);assert.equal(editor.invalid()[0],'Jerusalem-Tonga');
 editor.submitted();assert.deepEqual(Array.from(editor.values()),[]);assert.deepEqual(Array.from(editor.invalid()),['Jerusalem-Tonga']);assert.match(w.localStorage.getItem('tonga-country-draft-v1:TNG-S1:P1'),/Jerusalem-Tonga/);
 const other=w.document.createElement('div');w.TongaCountryInputs(other,'TNG-S1:P2',()=>{});assert.equal(other.querySelectorAll('.tonga-country-row').length,0,'Drafts scoped to publication');
 dom.window.close();console.log('PASS five fields, suggestions, invalid blur, canonical deduplication, draft restore, valid-only completion, publication scoping');
 const ui=new JSDOM('<button data-tab="scholar-submissions">Scholar</button><div data-tonga-queue="scholar"></div>',{runScripts:'outside-only'}),a=ui.window;a.confirm=()=>true;let reads=0,saves=[],failed=true;
 const rows=[1,2,3].map(n=>({'Submission ID':'S'+n,Status:'Pending',proposedChanges:[{key:'title',label:'Title',currentValue:'Old',newValue:'New',writable:true},{key:'gender',label:'Gender',currentValue:'M',newValue:'F',writable:true}]}));
 a.adminWriteback={isConfigured:()=>true,readScholarSubmissions:async()=>{reads++;return{status:'ok',rows}},reviewCapabilities:async()=>({status:'ok',version:'v4',selectionReview:true}),reviewScholarSelection:async(id,selected)=>{saves.push({id,selected});if(id==='S2'&&failed)throw Error('offline');return{status:'ok',row:{...rows.find(r=>r['Submission ID']===id),Status:'Reviewed'},remainingReview:false};}};
 a.eval(src('js/tongan-submissions-admin.js'));a.document.querySelector('[data-tab]').click();const tick=()=>new Promise(r=>setTimeout(r,15));await tick();
 const cards=a.document.querySelectorAll('.tonga-review');for(const i of [0,1]){const cb=cards[i].querySelector('input');cb.checked=true;cb.dispatchEvent(new a.Event('change',{bubbles:true}));}
 cards[0].querySelectorAll('table input')[1].checked=false;
 a.document.querySelector('.tonga-bulk-controls .tonga-approve').click();a.document.querySelector('.tonga-bulk-controls .tonga-approve').click();await tick();
 assert.equal(saves.length,2,'Double click causes no duplicate writes');assert.deepEqual(Array.from(saves[0].selected,x=>x.key),['title']);assert.equal(reads,1,'Successful batch never reloads full queue');assert.equal(a.document.querySelectorAll('.tonga-review').length,2);assert.match(a.document.querySelector('.tonga-queue-status').textContent,/Failed and retained/);assert(!saves.some(x=>x.id==='S3'),'Unchecked submission untouched');
 failed=false;a.document.querySelector('.tonga-bulk-controls .tonga-approve').click();await tick();assert.equal(saves.length,3);assert.equal(saves[2].id,'S2');assert.equal(a.document.querySelectorAll('.tonga-review').length,1);ui.window.close();console.log('PASS scholar bulk, per-field picks, unchecked pending, partial failure, retry only failed, duplicate clicks, no queue reload');
})().catch(e=>{console.error(e);process.exitCode=1});
