const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const {webcrypto}=require('node:crypto');
const {JSDOM}=require('jsdom');
const dom=new JSDOM('<div id="wrap"></div><span id="status"></span>');
const ctx={window:dom.window,TextEncoder,Uint8Array,console,module:{exports:{}}};
Object.defineProperty(dom.window,'crypto',{value:webcrypto});
vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/tongan-change-log.js','utf8'),ctx);
const api=ctx.module.exports;
const row={rowNumber:533,version:'admin-20260925-233840',date:'2026-09-25',actor:'Owner (legacy secret)',worksheet:'Publication Geography Submissions',field:'PGS-fixture',scope:'Owner (legacy secret) · TNG-S0001 · Publication Geography Submissions.PGS-fixture: Pending → Rejected',oldValue:'Pending',newValue:'Rejected',source:'fixture'};
const scholars={'TNG-S0001':{'Scholar Name':'Example scholar'}};
(async()=>{
 const legacy=await api.actor(row.actor);assert.equal(legacy.name,'Owner');assert.match(legacy.note,/individual not recorded/);
 const unknown=await api.actor('person@example.org (admin; Google 12345)');assert.equal(unknown.name,'person@example.org');assert.equal(unknown.role,'Admin');
 let r=api.normalize(row,scholars,{});assert.equal(r.scholar,'Example scholar');assert.equal(r.before,'Awaiting review');assert.equal(r.after,'Declined');assert.equal(r.action,'Geography suggestion declined');assert.equal(r.category,'Review decision');assert.equal(r.when.time,'11:38 pm');
 assert.equal(api.when({date:'2026-09-25',version:'release-1'}).time,'Time not recorded');
 const edit={...row,worksheet:'Positions',field:'Current institution',oldValue:'',newValue:'Example University'};
 r=api.normalize(edit,scholars,{});assert.equal(r.category,'Master data edit');assert.equal(r.before,'Not recorded / blank');assert.equal(r.after,'Example University');assert.equal(r.note,'');
 r=api.normalize({...edit,newValue:'Very long shortened value…'},scholars,{});assert.equal(r.shortened,true);
 const structural=api.normalize({change:'Added worksheet',scope:'Structural change'},scholars,{});assert.equal(structural.before,'Not available');assert.equal(structural.scholar,'Record not identified');
 r=api.normalize({...edit,newValue:'<img src=x onerror=alert(1)>'},scholars,{});r.actor=legacy;
 const html=api.renderRow(r);assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img'));assert.ok(html.includes('Technical details'));assert.ok(!html.includes('<details open'));
 const wrap=dom.window.document.querySelector('#wrap'),status=dom.window.document.querySelector('#status');
 let calls=0,resolveContext;const pending=new Promise(resolve=>resolveContext=resolve);
 await api.show({wrap,status,rows:[row,edit],scholars,client:{readGeographySubmissions(){calls++;return pending;}}});
 assert.equal(wrap.querySelectorAll('tbody tr').length,2,'initial history renders without waiting for title read');assert.equal(calls,1);
 const search=wrap.querySelector('#tcl-search');search.value='Example scholar';search.dispatchEvent(new dom.window.Event('input'));assert.equal(calls,1,'filters do not fetch');
 const select=wrap.querySelector('#tcl-type');select.value='Master data edit';select.dispatchEvent(new dom.window.Event('change'));assert.equal(wrap.querySelectorAll('tbody tr').length,1);
 resolveContext({status:'ok',rows:[{'Submission ID':'PGS-fixture','Scholar ID':'TNG-S0001','Publication Title':'Example paper','Proposed Other Countries':'Jerusalem - Tonga'}]});
 await new Promise(resolve=>setImmediate(resolve));assert.equal(select.value,'Master data edit','context enrichment retains filters');
 select.value='Review decision';select.dispatchEvent(new dom.window.Event('change'));assert.ok(wrap.textContent.includes('Example paper'));assert.ok(wrap.textContent.includes('not a historical before/after'));
 search.value='does-not-exist';search.dispatchEvent(new dom.window.Event('input'));assert.equal(wrap.querySelectorAll('tbody tr').length,0);assert.equal(wrap.querySelector('.tcl-empty').hidden,false);
 assert.equal(calls,1);
 console.log('PASS legacy attribution, status vs data edits, HST times, blank/unknown/truncated values, escaped text, nonblocking titles and local filters.');
})().catch(e=>{console.error(e);process.exitCode=1;});
