/* Run: NODE_PATH=<jsdom installation>/node_modules node tests/tongan-submissions.test.cjs */
const fs=require('fs'),assert=require('node:assert/strict'),crypto=require('crypto'),{JSDOM}=require('jsdom');
const src=p=>fs.readFileSync(p,'utf8');
const pass=Buffer.from(src('js/tongan-demo-gate.js').match(/BAKED_PASSCODE = atob\('([^']+)'/)[1],'base64');
async function fetchJson(p){if(!fs.existsSync(p+'.enc'))return JSON.parse(src(p));const b=fs.readFileSync(p+'.enc'),key=crypto.pbkdf2Sync(pass,b.subarray(4,20),200000,32,'sha256'),d=crypto.createDecipheriv('aes-256-gcm',key,b.subarray(20,32));d.setAuthTag(b.subarray(-16));return JSON.parse(Buffer.concat([d.update(b.subarray(32,-16)),d.final()]));}
const tick=()=>new Promise(r=>setTimeout(r,10));
(async()=>{
 const dom=new JSDOM(src('tongan-research-database-master.html'),{url:'https://ronvave.github.io/vave-lab/tongan-research-database-master.html',runScripts:'outside-only'}),w=dom.window;w.console={...console,error:()=>{}};w.dbGate={fetchJson,boot:()=>{}};w.fetch=async p=>({ok:true,json:()=>fetchJson(p)});w.alert=msg=>{throw Error(msg);};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.remove();};
 w.eval(src('js/tongan-database-adapter.js'));
 const dashboard=src('js/tongan-database-master.js');const pos=dashboard.lastIndexOf('})();');w.eval(dashboard.slice(0,pos)+'window.testTonga={state,loadAll,renderScholarCard,renderItemCard};'+dashboard.slice(pos));
 await w.testTonga.loadAll();const state=w.testTonga.state;
 const profile=Array.from(state.scholarProfilesByName.values()).find(p=>p.photo&&state.scholarInsights[p.name]);assert(profile,'Profile with saved photo and insight');
 const token='a'.repeat(40);let sent=[],enabled=true;w.fetch=async(url,options)=>({ok:true,json:async()=>{if(url.includes('tongan-share-tokens'))return{m:{[profile.scholarId]:token}};if(url.includes('submissionCapabilities'))return{status:'ok',country:'Tonga',publicSubmissionsEnabled:enabled};sent.push(JSON.parse(options.body));return{status:'ok',submissionId:'TEST'};}});
 w.eval(src('js/tongan-scholar-portal.js'));w.__tongaSharedScholar={scholarId:profile.scholarId,token};await w.TongaScholarPortal.renderShared(state,w.testTonga.renderScholarCard,w.testTonga.renderItemCard);
 assert.equal(w.document.querySelectorAll('.db-scholar-card').length,1);assert(w.document.querySelector('.db-scholar-card__photo').getAttribute('style').includes(profile.photo));assert(w.document.querySelector('.db-scholar-card__insight-summary').textContent.length>80);assert(!w.document.querySelector('#db-embed-b3-chord'));
 const linked=new Set(state.master.authorship.filter(a=>a['Scholar ID']===profile.scholarId).map(a=>a['Publication ID / BibTeX Key']));const expected=state.snapshot.items.filter(it=>linked.has(it._masterPublicationId));assert(expected.length>0);assert.equal(w.document.querySelectorAll('.tonga-geotag').length,expected.length);
 await w.TongaScholarPortal.openUpdate(profile,state);let form=w.document.querySelector('dialog form');const byLabel=s=>[...form.querySelectorAll('label')].find(l=>l.childNodes[0].textContent===s).querySelector('input,select,textarea');byLabel('Your name').value='Test reviewer';byLabel('Your email').value='test@example.invalid';byLabel('Relationship to this scholar').value='Self';byLabel('Professional title').value='Test changed title';await form.onsubmit({preventDefault(){}});assert.equal(sent.length,1);assert.deepEqual(Object.keys(sent[0].fields),['title']);assert.equal(sent[0].structuredSubmission.changedFieldsOnly,true);assert(!JSON.stringify(sent[0]).includes('secret'));w.document.querySelector('dialog').remove();
 w.document.querySelector('.tonga-geotag').click();form=w.document.querySelector('dialog form');byLabel('Your name').value='Test reviewer';byLabel('Your email').value='test@example.invalid';byLabel('Relationship to this scholar').value='Self';byLabel('Tonga — general / national study').checked=true;await form.onsubmit({preventDefault(){}});assert.equal(sent[1].changes[0].item_key,expected[0]._masterPublicationId);assert.equal(sent[1].changes[0].tonga_locations[0].national,true);w.document.querySelector('dialog').remove();
 enabled=false;await w.TongaScholarPortal.openUpdate(profile,state);form=w.document.querySelector('dialog form');byLabel('Your name').value='Test reviewer';byLabel('Your email').value='test@example.invalid';byLabel('Relationship to this scholar').value='Self';byLabel('Professional title').value='Another title';await form.onsubmit({preventDefault(){}});assert.equal(sent.length,2);assert.match(w.document.querySelector('dialog [role=status]').textContent,/not open yet/);
 console.log('PASS: shared profile preserves photo/insight, renders correct linked publications, submits changed fields only, uses Master publication ID, respects disabled submission gate.');dom.window.close();
 const admin=new JSDOM('<button data-tab="scholar-submissions"></button><button data-tab="geography-submissions"></button><div data-tonga-queue="scholar"></div><div data-tonga-queue="geography"></div>',{runScripts:'outside-only'}),a=admin.window;let approvals=[];a.confirm=()=>true;
 a.adminWriteback={isConfigured:()=>true,readScholarSubmissions:async()=>({status:'ok',rows:[{'Submission ID':'S1','Scholar ID':'TNG-S0001','Scholar Name':'<img src=x onerror=alert(1)>',Status:'Pending',proposedChanges:[{key:'title',label:'Title',currentValue:'Old',newValue:'New',writable:true},{key:'phd_year',label:'Year',currentValue:'',newValue:'2024',writable:false,reason:'Multiple degrees'}]}]}),approveScholarSubmission:async(...args)=>{approvals.push(args);return{status:'ok'};},readGeographySubmissions:async()=>({status:'ok',rows:[]})};a.eval(src('js/tongan-submissions-admin.js'));a.document.querySelector('[data-tab="scholar-submissions"]').click();await tick();assert(!a.document.querySelector('img'));const checks=a.document.querySelectorAll('input');assert(checks[0].checked&&!checks[0].disabled);assert(checks[1].disabled);[...a.document.querySelectorAll('button')].find(b=>b.textContent==='Approve checked fields').click();await tick();assert.equal(approvals.length,1);assert.equal(approvals[0][1].length,1);assert.equal(approvals[0][1][0].expectedCurrent,'Old');console.log('PASS: Admin escapes submitted text, excludes nonwritable fields, sends expected-current values.');admin.window.close();
})().catch(e=>{console.error(e);process.exit(1);});
