const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const M=require('../js/vanuatu-model.js'),D=require('../js/vanuatu-dashboard-model.js');
const c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync('js/vanuatu-preview-data.js','utf8'),c);const b=JSON.parse(JSON.stringify(c.window.VANUATU_PREVIEW));
let n=0;function test(name,f){f();console.log('PASS',name);n++;}
test('discipline degree totals are unions of scholar IDs',()=>{const x=structuredClone(b);x.tables['Graduate Degrees'].push({...x.tables['Graduate Degrees'][0],'Degree ID':'VAN-D9009'});const r=D.disciplines(M.build(x)).rows.find(r=>r.name==='Life and environmental sciences');assert.equal(r.masters.size,1);assert.equal(r.phd.size,1);assert.equal(r.total.size,1);});
test('ambiguous combined broad fields remain unmapped',()=>{assert.equal(D.shortDiscipline({'Broad Discipline':'Humanities and Social Sciences'}),'');assert.equal(D.shortDiscipline({'Broad Discipline':'Humanities and Social Sciences','Field / Discipline':'Sociology'}),'Social sciences');});
test('unique chronological degrees form a pathway without a new sheet',()=>{const x=structuredClone(b);x.tables['Study Pathways']=[];assert.equal(D.pathways(M.build(x)).rows.length,1);x.tables['Graduate Degrees'].push({...x.tables['Graduate Degrees'][0],'Degree ID':'VAN-D9009'});assert.equal(D.pathways(M.build(x)).rows.length,0);});
test('same publication deduplicates across coauthors at same origin',()=>{const x=structuredClone(b);x.tables.Scholars[1]['Paternal Province']='Sanma';x.tables.Authorship.push({'Scholar ID':'VAN-S9002','Publication ID':'VAN-P900001','Author Position':2});const m=M.build(x);assert.equal(D.byCommunity(m,[m.pubs[0]],'either').find(r=>r.name==='Sanma').pubs.length,1);});
test('research site never falls back to scholar origin',()=>{const x=structuredClone(b);x.tables['Research Geography']=[];const m=M.build(x);assert(D.byStudy(m,m.pubs).every(r=>r.name==='Location not yet coded'));});
test('study country is not international research scope',()=>{assert.equal(D.countryScope({'Country Focus':'Vanuatu'}),'vanuatu');assert.equal(D.countryScope({'University Country':'Australia'}),'unknown');});
test('BibTeX distinguishes thesis types and ordered authors',()=>{const bib=D.bibtex({'Publication ID':'VAN-P000001','Publication Type':"Master's Thesis",Title:'Example', 'Authors — Full Ordered List':'Vave, Ron; Example, Ana','Publisher / Institution':'Example University'});assert(bib.startsWith('@mastersthesis'));assert(bib.includes('Vave, Ron and Example, Ana'));assert(bib.includes('school = {Example University}'));});
test('all required panels and country-scoped dependencies exist',()=>{const h=fs.readFileSync('vanuatu-research-database-master.html','utf8');for(const p of ['a1','a2','a3','b1','b2','b3','b4','b5','c1','c2','c3','d','e','f','g'])assert(h.includes('class="db-panel__label">'+p.toUpperCase()+'</span>'),p);assert(!h.includes('js/tongan'));assert(h.includes('Graduate research disciplines'));});
console.log(n+' parity data checks passed.');
