"""Build the single-file Apps Script deployment; sources remain independently testable."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
target = root / "apps-script/deployed/solomon-submissions-v1.gs"
target.write_text(
    "// Generated by scripts/build_solomon_submission_bundle.py. Paste this entire file into the existing Solomon Apps Script project.\n"
    + (root / "apps-script/vendor/solomon-jwt.gs").read_text()
    + "\n"
    + (root / "apps-script/solomon-master-writeback.gs").read_text()
)
print(target.relative_to(root))
